# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rspec', '~> 3.8'
gem 'httparty', '~> 0.17.0'
gem 'nokogiri', '~> 1.10', '>= 1.10.4'
gem 'awesome_print', '~> 1.8'
gem 'prawn', '~> 2.2', '>= 2.2.2'
gem 'rubyXL', '~> 3.4', '>= 3.4.6'